controller_manager:
  ros__parameters:
    update_rate: 1000

    # Definieer elke controller en zijn type
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Definieer de parameters voor elke controller apart.

diff_drive_base_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
    
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.182
    wheel_radius: 0.029

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    use_stamped_vel: false

    # Snelheids- en acceleratielimieten
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

# De joint_state_broadcaster heeft meestal geen extra parameters nodig,
# tenzij je specifiek wilt aangeven welke joints/interfaces hij moet publiceren.
joint_state_broadcaster:
  ros__parameters: {}


joint_trajectory_controller:
  ros__parameters:           
    joints:
      - bovenwagen_joint
      - giek_joint
      - jib_joint
      - adapter_grijper_joint
      - grijper_joint
    
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    # === DE WIJZIGINGEN ZIJN HIER ===
    
    # 1. Sta commando's toe die niet alle joints specificeren (maakt het robuuster)
    allow_partial_joints_goal: true
    
    # 2. Stel de publicatiefrequentie voor de interne staat in.
    #    Een waarde van 50 Hz is gebruikelijk. Dit stabiliseert de output.
    state_publish_rate: 50.0

    # 3. Voeg toleranties toe. Dit helpt de controller te bepalen wanneer een doel is bereikt.
    goal_tolerances:
      bovenwagen_joint: 0.01
      giek_joint: 0.01
      jib_joint: 0.01
      adapter_grijper_joint: 0.01
      grijper_joint: 0.01
    
    gains:
      bovenwagen_joint:      {p: 10.0, i: 0.0, d: 1.0}
      giek_joint:            {p: 10.0, i: 0.0, d: 1.0}
      jib_joint:             {p: 10.0, i: 0.0, d: 1.0}
      adapter_grijper_joint: {p: 5.0,  i: 0.0, d: 0.5}
      grijper_joint:         {p: 5.0,  i: 0.0, d: 0.5}
    
   

    
    