# ~/rmb/src/rmb_db/rmb_description/config/motor_configs.yaml
joint_names:
    - left_wheel_joint
    - right_wheel_joint
    - bovenwagen_joint
    - giek_joint
    - jib_joint
    - adapter_grijper_joint
    - grijper_joint

# Configuratie voor elk afzonderlijk gewricht
joint_profiles:
    left_wheel_joint:
        # Type controller (e.g., 'velocity', 'position', 'extended_position')
        # Dit is alleen voor interne logging en initialisatie; de werkelijke command_interface komt uit de URDF.
        # Voor een wiel kun je 'velocity' of 'position' gebruiken als de Dynamixel in die modus staat
        type: velocity 
        # Model van de Dynamixel
        motor_type: XL-340-W250-T # BIJVOORBEELD: XL330-M288-T of XL-340-W250-T
        motor_id: 1
        # Home positie (rad) - Niet altijd relevant voor wielen in velocity control
        initial_position: 0.0
        # Joint limits (rad) - Niet altijd relevant voor wielen in velocity control
        # Pas deze aan op basis van de mechanische limieten van je robot
        joint_limits:
            lower: -3.14  # -180 graden
            upper: 3.14   # 180 graden
            velocity: 12.0 # max rad/s
            # Koppel limieten kunnen hier ook, indien nodig
    
    right_wheel_joint:
        type: velocity
        motor_type: XL-340-W250-T
        motor_id: 2
        initial_position: 0.0
        joint_limits:
            lower: -3.14
            upper: 3.14
            velocity: 12.0

    bovenwagen_joint:
        type: extended_position # Voor positie aansturing
        motor_type: XL-340-W250-T
        motor_id: 3
        initial_position: 0.0 # Beginpositie (rad)
        joint_limits:
            lower: -2.5172 # Bijv. -90 graden
            upper: 1.853  # Bijv. 90 graden
            velocity: 12.0 # max rad/s
            #acceleration: 0.5 # Optioneel, afhankelijk van Dynamixel model en firmware
    
    giek_joint:
        type: extended_position
        motor_type: XL-340-W250-T
        motor_id: 4
        initial_position: 0.0
        joint_limits:
            lower: -1.6766
            upper: 2.0356
            velocity: 12.0

    jib_joint:
        type: extended_position
        motor_type: XL-340-W250-T
        motor_id: 5
        initial_position: 0.0
        joint_limits:
            lower: -2.2902
            upper: 2.3731
            velocity: 12.0
    
    adapter_grijper_joint:
        type: extended_position
        motor_type: XL-340-W250-T
        motor_id: 6
        initial_position: 0.0
        joint_limits:
            lower: -1.5615
            upper: 1.6597
            velocity: 0.5

    grijper_joint:
        type: extended_position
        motor_type: XL-340-W250-T
        motor_id: 7
        initial_position: 0.0
        joint_limits:
            lower: -0.3
            upper: 0.3
            velocity: 1.0